apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: bevo
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: bevo
    app.kubernetes.io/part-of: byoc-app-osno
  name: bevo
spec:
  rules:
  - host: bevo-byoc-oiza-tenant.apps.3243ce80330c9132c109.hypershift.aws-2.ci.openshift.org
    http:
      paths:
      - backend:
          service:
            name: bevo
            port:
              number: 8081
        path: /
        pathType: ImplementationSpecific
status:
  loadBalancer: {}
