apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: bevo
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: bevo
    app.kubernetes.io/part-of: byoc-app-osno
  name: bevo
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: bevo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: bevo
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/byoc-oiza-tenant/byoc-app-osno/bevo@sha256:3a33855e7fb9e10c2a9e5f0f5180b11df8b93793fa5f105fc0f1da9e328d825c
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
